server {
    listen ${PORT};
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    absolute_redirect off;
    port_in_redirect off;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript application/wasm;

    location ~* \.(?:js|css|woff2?|ttf|otf|svg|png|jpg|jpeg|gif|webp|ico)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    location = / {
        if ($host = cercles.citurbarea.com) {
            return 302 /cercles;
        }
        try_files /index.html =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
