[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node ./node_modules/prisma/build/index.js migrate deploy --schema prisma/schema.prisma && node ./node_modules/prisma/build/index.js migrate deploy --schema prisma/dossiers/schema.prisma && node apps/api/dist/main.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
