/**
 * Textes du gadget de chiffrage. Dictionnaire local (FR / EN / AR) pour que
 * le chunk /chiffrage reste autonome et chargé à la demande ; les libellés
 * techniques des ouvrages restent en français (vocabulaire des CPS).
 */
import type { Lang } from "../../i18n/i18n";

const FR = {
  kicker: "Chiffrage lot par lot",
  titre: "Combien va coûter votre villa ?",
  sousTitre: "Un vrai métré : fondations, sous-sol, pente, puis chaque lot jusqu'aux finitions. Prix 2026 sourcés, hypothèses visibles et modifiables.",
  etape1: "Projet",
  etape2: "Terrain et fondations",
  etape3: "Finitions par lot",
  etape2court: "Terrain",
  etape3court: "Finitions",
  suivant: "Étape suivante",
  precedent: "Retour",
  voirResultat: "Voir le résultat",
  type: "Type de projet",
  "type.VILLA": "Villa",
  "type.MAISON": "Maison R+1 / R+2",
  "type.IMMEUBLE": "Immeuble R+N",
  "type.MIXTE": "Immeuble mixte",
  ville: "Ville",
  autreVille: "Autre ville",
  surface: "Surface de plancher (hors sous-sol)",
  niveaux: "Niveaux",
  standing: "Niveau de standing",
  chambres: "Chambres",
  sdb: "Salles de bain",
  logements: "Logements",
  terrain: "Surface du terrain",
  emprise: "Emprise au sol du bâtiment",
  auto: "auto",
  hsp: "Hauteur sous plafond",
  mitoyennete: "Côtés mitoyens",
  sol: "Nature du sol",
  "sol.ROCHER": "Rocher",
  "sol.BON": "Bon sol",
  "sol.MOYEN": "Sol moyen",
  "sol.ARGILE_REMBLAI": "Argile ou remblai",
  "solAide.ROCHER": "Semelles isolées, déblai au brise-roche",
  "solAide.BON": "Semelles isolées (2 à 3 bars)",
  "solAide.MOYEN": "Semelles filantes élargies",
  "solAide.ARGILE_REMBLAI": "Radier général + purge et substitution",
  solInconnu: "Vous ne savez pas ? Laissez « Bon sol » : l'étude de sol (géotechnicien) tranchera, et elle est comptée dans les honoraires.",
  pente: "Pente du terrain",
  sousSol: "Sous-sol",
  profondeur: "Profondeur de terre à soutenir",
  nappe: "Présence d'eau (nappe) : cuvelage et pompage",
  cloture: "Clôture",
  portail: "Portail",
  terrasseAccessible: "Toit-terrasse accessible",
  terrasses: "Balcons et terrasses carrelés",
  finitionsAide: "Par défaut, chaque lot suit le standing choisi. Changez-en un pour voir son poids exact.",
  options: "Équipements et options",
  clim: "Climatisation",
  solaire: "Chauffe-eau solaire",
  piscine: "Piscine (m² de plan d'eau)",
  ascenseur: "Ascenseur / élévateur",
  pv: "Photovoltaïque (kWc)",
  cuisine: "Cuisine équipée (ml)",
  oui: "Oui",
  non: "Non",
  resultat: "Votre estimation",
  travauxTTC: "Travaux TTC",
  travauxHT: "Travaux HT",
  coutM2: "soit {v} DH HT/m² de plancher (bâtiment seul, hors clôture et options)",
  typeVilla: "Type de villa",
  "villa.isolee": "Isolée (CES 0,3)",
  "villa.jumelee": "Jumelée (CES 0,4)",
  "villa.bande": "En bande (CES 0,5)",
  typeImmeuble: "Type d'immeuble",
  "imm.standard": "Standard (CES 1,0)",
  "imm.maison_ville": "Maison de ville (CES 0,7)",
  "imm.rdc_commercial": "RDC commercial",
  facades: "Façades",
  facade1: "1 façade",
  facade2: "2 façades ou plus",
  galerie: "Galerie au RDC (recul, CES 0,7)",
  cour: "Cour (1 façade)",
  "cour.unknown": "À étudier (hypothèse haute)",
  "cour.with_cour": "Avec cour",
  "cour.without_cour": "Sans cour (cour de jour par étage)",
  courSurface: "Surface de la cour",
  voieLarge: "Voie ≥ 12 m (porte-à-faux, étages × 1,1)",
  surfaceCalculee: "Surface plancher calculée (règle CITURBAREA : CES, étages, sous-sol, forfait)",
  forfait: "cage, buanderie et terrasse",
  saisieDirecte: "Saisir les surfaces moi-même",
  calculParcelle: "Calculer depuis le terrain (règle CES)",
  regime: "Mode de réalisation",
  regimeAuto: "Automatique",
  regimeAide: "Le très économique se réalise par tâcheron (15 à 20 % moins cher) ; les autres standings par une entreprise générale.",
  parTacheron: "tâcheron",
  fourchette: "Fourchette : {min} – {max} TTC",
  precision: "Précision",
  niveau: "Niveau {n}",
  precisionQte: "quantités ±{q} %",
  precisionPrix: "prix ±{p} %",
  precisionAide: "Niveau 1 : ratios. Niveau 2 : métré paramétrique (étapes 2 et 3 validées). Niveau 3 : quantités saisies sur plans dans le détail.",
  impactSousSol: "Votre sous-sol ajoute {m} HT, dont {s} de soutènement (voile, drainage, étanchéité).",
  impactSol: "La nature du sol ajoute {m} HT par rapport à un bon sol.",
  impactPente: "La pente ajoute {m} HT, dont {s} de murs de soutènement.",
  parLot: "Coût par lot",
  budget: "Budget global",
  honoraires: "Honoraires (architecte, BET, études)",
  taxes: "Taxes et autorisations",
  raccordements: "Raccordements",
  aleas: "Aléas et imprévus",
  tva: "TVA (20 %)",
  budgetTotal: "Budget total TTC",
  comparaison: "Comparer les standings",
  detail: "Détail du DQE (devis quantitatif estimatif)",
  hypotheses: "Hypothèses du calcul",
  hypothesesAide: "Chaque ratio est une hypothèse de calcul : modifiez-la si votre architecte ou votre BET en a une meilleure.",
  reinitialiser: "Réinitialiser",
  controles: "Contrôles de cohérence",
  imprimer: "Imprimer / PDF du DQE",
  cta: "Recevoir mon estimation détaillée",
  ctaSous: "Un architecte CITURBAREA vérifie votre DQE et vous rappelle. Gratuit et sans engagement.",
  formTitre: "Recevez votre DQE vérifié",
  quantiteSaisie: "Quantité (modifiable)",
  sousDetail: "Sous-détail du prix",
  sources: "Sources",
  avertissement: "Estimation indicative, hors terrain, mobilier et électroménager. Prix 2026 base Rabat-Salé-Kénitra, régionalisés. Les valeurs marquées H sont des hypothèses CITURBAREA : remplacez-les par vos devis.",
};

type Cle = keyof typeof FR;

const EN: Partial<Record<Cle, string>> = {
  kicker: "Line-by-line cost estimate",
  titre: "How much will your villa cost?",
  sousTitre: "A real quantity take-off: foundations, basement, slope, then every trade down to finishes. Sourced 2026 prices, visible and editable assumptions.",
  etape1: "Project", etape2: "Site and foundations", etape3: "Finishes by trade", etape2court: "Site", etape3court: "Finishes",
  suivant: "Next step", precedent: "Back", voirResultat: "See the result",
  type: "Project type", "type.VILLA": "Villa", "type.MAISON": "House (2-3 storeys)", "type.IMMEUBLE": "Apartment building", "type.MIXTE": "Mixed-use building",
  ville: "City", autreVille: "Other city", surface: "Floor area (excluding basement)", niveaux: "Storeys", standing: "Standard",
  chambres: "Bedrooms", sdb: "Bathrooms", logements: "Units", terrain: "Plot area", emprise: "Building footprint", auto: "auto",
  hsp: "Ceiling height", mitoyennete: "Party walls", sol: "Soil", "sol.ROCHER": "Rock", "sol.BON": "Good soil", "sol.MOYEN": "Average soil", "sol.ARGILE_REMBLAI": "Clay or fill",
  "solAide.ROCHER": "Pad footings, rock breaking", "solAide.BON": "Pad footings (2-3 bar)", "solAide.MOYEN": "Wide strip footings", "solAide.ARGILE_REMBLAI": "Raft + soil replacement",
  solInconnu: "Not sure? Keep “Good soil”: the soil survey will decide, and it is included in the fees.",
  pente: "Plot slope", sousSol: "Basement", profondeur: "Depth of retained soil", nappe: "Groundwater: tanking and pumping",
  cloture: "Boundary wall", portail: "Gate", terrasseAccessible: "Accessible roof terrace", terrasses: "Tiled balconies and terraces",
  finitionsAide: "By default each trade follows the chosen standard. Change one to see its exact weight.",
  options: "Equipment and options", clim: "Air conditioning", solaire: "Solar water heater", piscine: "Pool (m² of water)", ascenseur: "Lift", pv: "Solar PV (kWp)", cuisine: "Fitted kitchen (lm)",
  oui: "Yes", non: "No", resultat: "Your estimate", travauxTTC: "Works incl. VAT", travauxHT: "Works excl. VAT", coutM2: "i.e. {v} MAD excl. VAT per m² (building only)", typeVilla: "Villa type", "villa.isolee": "Detached (CES 0.3)", "villa.jumelee": "Semi-detached (CES 0.4)", "villa.bande": "Terraced (CES 0.5)", typeImmeuble: "Building type", facades: "Frontages", facade1: "1 frontage", facade2: "2 or more", voieLarge: "Street ≥ 12 m (overhang, floors × 1.1)", surfaceCalculee: "Floor area computed (CITURBAREA rule: CES, floors, basement, lump sum)", forfait: "stairwell, laundry and terrace", saisieDirecte: "Enter areas myself", calculParcelle: "Compute from the plot (CES rule)", regime: "Contracting mode", regimeAuto: "Automatic", parTacheron: "jobber",
  fourchette: "Range: {min} – {max} incl. VAT", precision: "Accuracy", niveau: "Level {n}", precisionQte: "quantities ±{q}%", precisionPrix: "prices ±{p}%",
  precisionAide: "Level 1: ratios. Level 2: parametric take-off (steps 2 and 3 confirmed). Level 3: quantities measured on drawings, entered in the detail.",
  impactSousSol: "Your basement adds {m} excl. VAT, including {s} of retaining structure (wall, drainage, waterproofing).",
  impactSol: "The soil adds {m} excl. VAT compared with good soil.", impactPente: "The slope adds {m} excl. VAT, including {s} of retaining walls.",
  parLot: "Cost by trade", budget: "Overall budget", honoraires: "Fees (architect, engineers, surveys)", taxes: "Taxes and permits", raccordements: "Utility connections",
  aleas: "Contingency", tva: "VAT (20%)", budgetTotal: "Total budget incl. VAT", comparaison: "Compare standards", detail: "Bill of quantities",
  hypotheses: "Calculation assumptions", hypothesesAide: "Every ratio is an assumption: change it if your architect or engineer has a better one.", reinitialiser: "Reset",
  controles: "Consistency checks", imprimer: "Print / PDF", cta: "Get my detailed estimate", ctaSous: "A CITURBAREA architect checks your bill of quantities and calls you back. Free, no commitment.",
  formTitre: "Receive your checked estimate", quantiteSaisie: "Quantity (editable)", sousDetail: "Unit price breakdown", sources: "Sources",
  avertissement: "Indicative estimate, excluding land, furniture and appliances. 2026 prices, Rabat-Salé-Kénitra base, adjusted by city. Values marked H are CITURBAREA assumptions: replace them with your quotes.",
};

const AR: Partial<Record<Cle, string>> = {
  kicker: "تقدير التكلفة حسب الحصص",
  titre: "كم ستكلف فيلتك؟",
  sousTitre: "قياس حقيقي للكميات: الأساسات، الطابق تحت الأرضي، الانحدار، ثم كل حصة حتى التشطيبات. أسعار 2026 موثقة وفرضيات ظاهرة وقابلة للتعديل.",
  etape1: "المشروع", etape2: "الأرض والأساسات", etape3: "التشطيبات حسب الحصة", etape2court: "الأرض", etape3court: "التشطيبات",
  suivant: "الخطوة التالية", precedent: "رجوع", voirResultat: "عرض النتيجة",
  type: "نوع المشروع", "type.VILLA": "فيلا", "type.MAISON": "منزل (طابقان أو ثلاثة)", "type.IMMEUBLE": "عمارة سكنية", "type.MIXTE": "عمارة مختلطة",
  ville: "المدينة", autreVille: "مدينة أخرى", surface: "المساحة المغطاة (دون الطابق تحت الأرضي)", niveaux: "الطوابق", standing: "مستوى التشطيب",
  chambres: "غرف النوم", sdb: "الحمامات", logements: "الشقق", terrain: "مساحة البقعة", emprise: "مساحة البناء على الأرض", auto: "تلقائي",
  hsp: "علو السقف", mitoyennete: "الجدران المشتركة", sol: "طبيعة التربة", "sol.ROCHER": "صخر", "sol.BON": "تربة جيدة", "sol.MOYEN": "تربة متوسطة", "sol.ARGILE_REMBLAI": "طين أو ردم",
  pente: "انحدار الأرض", sousSol: "طابق تحت أرضي", profondeur: "عمق التربة المسنودة", nappe: "وجود مياه جوفية",
  cloture: "السور", portail: "البوابة", options: "التجهيزات والاختيارات", clim: "التكييف", solaire: "سخان شمسي", piscine: "مسبح (م²)", ascenseur: "مصعد", pv: "طاقة شمسية (kWc)", cuisine: "مطبخ مجهز (م.ط)",
  oui: "نعم", non: "لا", resultat: "تقديرك", travauxTTC: "الأشغال مع الضريبة", travauxHT: "الأشغال دون الضريبة", precision: "الدقة", niveau: "المستوى {n}",
  parLot: "التكلفة حسب الحصة", budget: "الميزانية الإجمالية", honoraires: "أتعاب المهندس المعماري والدراسات", taxes: "الرسوم والرخص", raccordements: "الربط بالشبكات",
  aleas: "احتياطي الطوارئ", tva: "الضريبة على القيمة المضافة (20%)", budgetTotal: "الميزانية الإجمالية مع الضريبة", comparaison: "مقارنة المستويات", detail: "الكشف التقديري للكميات",
  hypotheses: "فرضيات الحساب", reinitialiser: "إعادة الضبط", controles: "مراقبة الانسجام", imprimer: "طباعة / PDF", cta: "توصل بتقديرك المفصل",
  ctaSous: "يراجع مهندس معماري من CITURBAREA الكشف ويتصل بك. مجاناً ودون التزام.", formTitre: "توصل بالكشف بعد مراجعته", sources: "المصادر",
  avertissement: "تقدير إرشادي دون احتساب ثمن الأرض والأثاث والأجهزة. أسعار 2026 على أساس الرباط-سلا-القنيطرة مع معامل المدينة. القيم المرموز لها بـ H فرضيات: عوضها بعروض الأسعار.",
};

export function texte(lang: Lang) {
  const d = lang === "en" ? EN : lang === "ar" ? AR : {};
  return (cle: Cle, vars?: Record<string, string | number>) => {
    let s = d[cle] ?? FR[cle];
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(`{${k}}`, String(v));
    return s;
  };
}

/** Libellés courts des gammes de finition par lot (index = standing ULTRA_ECO → PREMIUM). */
export const GAMMES_LIBELLES: Record<string, { lot: string; gammes: string[] }> = {
  RSO: { lot: "Sols", gammes: ["Grès 45×45", "Grès 60×60", "Grès grand format", "Marbre local", "Marbre importé"] },
  RMU: { lot: "Faïence", gammes: ["Faïence courante", "Faïence courante", "Faïence décor", "Faïence décor", "Zellige"] },
  PEI: { lot: "Peinture", gammes: ["Vinylique éco", "Vinylique lessivable", "Vinylique lessivable", "Acrylique haut de gamme", "Acrylique haut de gamme"] },
  FPL: { lot: "Plafonds", gammes: ["Enduit, sans faux plafond", "BA13 sur 30 %", "BA13 sur 60 %", "BA13 + staff 40 %", "Staff décoratif 70 %"] },
  ALU: { lot: "Fenêtres", gammes: ["Alu sans RPT", "Alu RPT double vitrage", "Alu RPT grandes baies", "+ 30 % levant-coulissant", "+ 70 % levant-coulissant"] },
  BOI: { lot: "Portes", gammes: ["Isoplane", "Bloc-porte", "Pin massif", "Chêne massif", "Chêne massif"] },
  MET: { lot: "Garde-corps", gammes: ["Aluminium", "Inox", "Verre et inox", "Verre et inox", "Tout verre"] },
  PLO: { lot: "Sanitaires", gammes: ["Éco (cabine de douche)", "Courant (douche italienne)", "Haut de gamme (WC suspendu)", "Luxe (douche encastrée)", "Luxe (douche encastrée)"] },
  ELE: { lot: "Électricité", gammes: ["Standard", "Standard", "Appareillage design", "Design, plus de points", "Design, densité luxe"] },
  FAC: { lot: "Façade", gammes: ["Enduit + vinylique", "Enduit + vinylique", "Siloxane + 10 % pierre", "Siloxane + 25 % pierre", "Siloxane + 50 % pierre"] },
};

export const VILLES = [
  "Casablanca", "Bouskoura", "Mohammedia", "Rabat", "Salé", "Témara", "Kénitra", "Tanger", "Tétouan",
  "Marrakech", "Agadir", "Fès", "Meknès", "Oujda", "El Jadida",
];
