/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 * Generated by scripts/generate-route-audit.mjs
 */
export const DECLARED_ROUTES = [
  "/auth/login",
  "/auth/signup",
  "/p1/config",
  "/p1/confirmation",
  "/p1/qualification",
  "/p1/qualify",
  "/p1/offres",
  "/p1/packs-personnalise",
  "/media",
  "/p2",
  "/p2/form",
  "/p2/result",
  "/p3",
  "/p4",
  "/p5",
  "/p6",
  "/enterprise/api",
  "/forbidden",
  "/upgrade",
  "/faq",
  "/",
  "/login",
  "/p1",
  "/p1/packs",
  "/p1/dossier",
  "/_dev/routes"
] as const;
export const ROUTE_USAGES = [
  {
    "route": "/cc",
    "file": "src/ui/simulateur/SimulatorPage.tsx",
    "line": 44
  },
  {
    "route": "/login",
    "file": "src/ui/landing/CTASection.tsx",
    "line": 26
  },
  {
    "route": "/cercles",
    "file": "src/ui/landing/DoorsSection.tsx",
    "line": 62
  },
  {
    "route": "/",
    "file": "src/ui/landing/DoorsSection.tsx",
    "line": 65
  },
  {
    "route": "/login",
    "file": "src/ui/landing/FooterSection.tsx",
    "line": 34
  },
  {
    "route": "/login",
    "file": "src/ui/landing/FooterSection.tsx",
    "line": 35
  },
  {
    "route": "/media",
    "file": "src/ui/landing/FooterSection.tsx",
    "line": 53
  },
  {
    "route": "/login",
    "file": "src/ui/landing/HeroSection.tsx",
    "line": 45
  },
  {
    "route": "/login",
    "file": "src/ui/landing/HeroSection.tsx",
    "line": 115
  },
  {
    "route": "/p1",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 688
  },
  {
    "route": "/p1",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 707
  },
  {
    "route": "/p2",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 711
  },
  {
    "route": "/p3",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 715
  },
  {
    "route": "/p4",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 719
  },
  {
    "route": "/p5",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 723
  },
  {
    "route": "/p6",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 727
  },
  {
    "route": "/login",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 751
  },
  {
    "route": "/creer-compte",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 752
  },
  {
    "route": "/p1",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 771
  },
  {
    "route": "/p2",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 777
  },
  {
    "route": "/p3",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 783
  },
  {
    "route": "/p4",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 789
  },
  {
    "route": "/p5",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 795
  },
  {
    "route": "/p6",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 801
  },
  {
    "route": "/media",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1230
  },
  {
    "route": "/media",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1244
  },
  {
    "route": "/cc",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 221
  },
  {
    "route": "/p1",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 225
  },
  {
    "route": "/p2",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 226
  },
  {
    "route": "/p3",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 227
  },
  {
    "route": "/p4",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 228
  },
  {
    "route": "/p5",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 229
  },
  {
    "route": "/p6",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 230
  },
  {
    "route": "/cc",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 241
  },
  {
    "route": "/cc",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 252
  },
  {
    "route": "/",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 311
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/guards.tsx",
    "line": 10
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/guards.tsx",
    "line": 18
  },
  {
    "route": "/forbidden",
    "file": "src/tomes/tome5/guards.tsx",
    "line": 19
  },
  {
    "route": "/upgrade",
    "file": "src/tomes/tome5/guards.tsx",
    "line": 27
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/AccountTypeChooser.tsx",
    "line": 25
  },
  {
    "route": "/inscription",
    "file": "src/tomes/tome5/pages/AccountTypeChooser.tsx",
    "line": 31
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/AccountTypeChooser.tsx",
    "line": 55
  },
  {
    "route": "/creer-compte",
    "file": "src/tomes/tome5/pages/ClientSignup.tsx",
    "line": 114
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/ClientSignup.tsx",
    "line": 212
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/Forbidden.tsx",
    "line": 15
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/Forbidden.tsx",
    "line": 16
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/ForgotPassword.tsx",
    "line": 87
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/ForgotPassword.tsx",
    "line": 146
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 71
  },
  {
    "route": "/mot-de-passe-oublie",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 184
  },
  {
    "route": "/cercles",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 39
  },
  {
    "route": "/p1/packs",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 44
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/Signup.tsx",
    "line": 57
  },
  {
    "route": "/auth/login",
    "file": "src/tomes/tome5/pages/Signup.tsx",
    "line": 205
  },
  {
    "route": "/p1/packs",
    "file": "src/tomes/tome5/pages/Signup.tsx",
    "line": 30
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome5/pages/SignupSMS.tsx",
    "line": 29
  },
  {
    "route": "/auth/login",
    "file": "src/tomes/tome5/pages/SignupSMS.tsx",
    "line": 331
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/Upgrade.tsx",
    "line": 15
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/Upgrade.tsx",
    "line": 16
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome5/components/ClientProfileBanner.tsx",
    "line": 62
  },
  {
    "route": "/cc/login",
    "file": "src/tomes/tome4/apiClient.ts",
    "line": 96
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 80
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 136
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 137
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 158
  },
  {
    "route": "/login",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 38
  },
  {
    "route": "/p6",
    "file": "src/tomes/tome3/portals/p6/P6Dashboard.tsx",
    "line": 167
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/p6/P6Home.tsx",
    "line": 233
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 27
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 33
  },
  {
    "route": "/p5",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 40
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 96
  },
  {
    "route": "/p5",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 106
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 107
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 94
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 446
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 561
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 562
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 560
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p4/P4Home.tsx",
    "line": 212
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/p4/P4Home.tsx",
    "line": 213
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p4/P4Home.tsx",
    "line": 211
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p3/P3Home.tsx",
    "line": 216
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/p3/P3Home.tsx",
    "line": 217
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p3/P3Home.tsx",
    "line": 215
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 27
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 34
  },
  {
    "route": "/p2",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 41
  },
  {
    "route": "/p5",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 70
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 110
  },
  {
    "route": "/p2",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 120
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 121
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 106
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 692
  },
  {
    "route": "/p5",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 723
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 812
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 813
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 1211
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 811
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1ClientPhases.tsx",
    "line": 146
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1Dossier.tsx",
    "line": 49
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1Dossier.tsx",
    "line": 46
  },
  {
    "route": "/p1/dossier/phases",
    "file": "src/tomes/tome3/portals/p1/P1Dossier.tsx",
    "line": 67
  },
  {
    "route": "/p1/packs",
    "file": "src/tomes/tome3/portals/p1/P1Landing.tsx",
    "line": 878
  },
  {
    "route": "/auth/login",
    "file": "src/tomes/tome3/portals/p1/P1Landing.tsx",
    "line": 2144
  },
  {
    "route": "/login",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 67
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 84
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 101
  },
  {
    "route": "/p1/dossier",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 137
  },
  {
    "route": "/p1/dossier/phases",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 140
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 143
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1OffersAndTunnel.tsx",
    "line": 37
  },
  {
    "route": "/login",
    "file": "src/tomes/tome3/portals/p1/P1OffersAndTunnel.tsx",
    "line": 43
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 615
  },
  {
    "route": "/login",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 164
  },
  {
    "route": "/verify-phone",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 168
  },
  {
    "route": "/p1/dossier",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 355
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 41
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 49
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 58
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 63
  },
  {
    "route": "/p1/config",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 133
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 241
  },
  {
    "route": "/faq",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 495
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 41
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 46
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 48
  },
  {
    "route": "/login",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 50
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 97
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 170
  },
  {
    "route": "/cc/dashboard",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 88
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 115
  },
  {
    "route": "/cc/dashboard",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 128
  },
  {
    "route": "/admin/login",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 143
  },
  {
    "route": "/cercles",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 202
  },
  {
    "route": "/login",
    "file": "src/features/media/components/ArticleCard.tsx",
    "line": 263
  },
  {
    "route": "/media",
    "file": "src/features/media/components/ArticleCard.tsx",
    "line": 213
  },
  {
    "route": "/cercles/me/profile",
    "file": "src/features/cercles/AnnuairePage.tsx",
    "line": 127
  },
  {
    "route": "/cercles/profile/",
    "file": "src/features/cercles/AnnuairePage.tsx",
    "line": 135
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/AssociationApplyPage.tsx",
    "line": 136
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 130
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 135
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 141
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 149
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 230
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 451
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 452
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 34
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 37
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 38
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 59
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 62
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 63
  },
  {
    "route": "/cercles/snasp-architectes-prive/rejoindre",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 93
  },
  {
    "route": "/cercles/anjaum-jeunes-architectes/rejoindre",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 112
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 196
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 199
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 200
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 214
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 215
  },
  {
    "route": "/",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 103
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 49
  },
  {
    "route": "/p1",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 60
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 68
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 88
  },
  {
    "route": "/cercles/nouveau",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 134
  },
  {
    "route": "/cercles/messages",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 137
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 145
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 148
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 183
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 199
  },
  {
    "route": "/cercles/messages",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 93
  },
  {
    "route": "/cercles/messages/",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 89
  },
  {
    "route": "/cercles/profile/",
    "file": "src/features/cercles/EditProfilePage.tsx",
    "line": 194
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 219
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 291
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 134
  },
  {
    "route": "/post/",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 233
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 234
  },
  {
    "route": "/",
    "file": "src/features/cercles/InscriptionPage.tsx",
    "line": 316
  },
  {
    "route": "/",
    "file": "src/features/cercles/InscriptionPage.tsx",
    "line": 567
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 58
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 65
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 102
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 108
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 121
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/NewCerclePage.tsx",
    "line": 83
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/NewCerclePage.tsx",
    "line": 24
  },
  {
    "route": "/cercles/me/edit",
    "file": "src/features/cercles/ProfilePage.tsx",
    "line": 183
  },
  {
    "route": "/cercles/messages/new/",
    "file": "src/features/cercles/ProfilePage.tsx",
    "line": 188
  },
  {
    "route": "/",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 50
  },
  {
    "route": "/login",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 58
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 59
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 72
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 145
  },
  {
    "route": "/login",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 146
  },
  {
    "route": "/cercles/marketplace/photos",
    "file": "src/features/cercles/marketplace/MarketplacePage.tsx",
    "line": 57
  },
  {
    "route": "/cercles/mes-offres",
    "file": "src/features/cercles/marketplace/MarketplacePage.tsx",
    "line": 58
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/marketplace/MarketplacePhotosPage.tsx",
    "line": 69
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/marketplace/MyOffersPage.tsx",
    "line": 65
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/marketplace/ProductDetailPage.tsx",
    "line": 36
  },
  {
    "route": "/cercles/mes-offres",
    "file": "src/features/cercles/marketplace/ProductDetailPage.tsx",
    "line": 69
  },
  {
    "route": "/cercles/messages/new/",
    "file": "src/features/cercles/marketplace/ProductDetailPage.tsx",
    "line": 95
  },
  {
    "route": "/admin/users",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 70
  },
  {
    "route": "/admin/cercles",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 71
  },
  {
    "route": "/admin/audit",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 72
  },
  {
    "route": "/admin/admins",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 73
  },
  {
    "route": "/admin/security",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 74
  },
  {
    "route": "/admin/audit",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 131
  },
  {
    "route": "/admin/users",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 171
  },
  {
    "route": "/admin/security/webauthn",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 175
  },
  {
    "route": "/admin/security/ips",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 179
  },
  {
    "route": "/admin/admins/new",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 184
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 27
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 43
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 53
  },
  {
    "route": "/admin/dashboard",
    "file": "src/features/admin/AdminLoginPage.tsx",
    "line": 36
  },
  {
    "route": "/admin/security/webauthn",
    "file": "src/features/admin/AdminLoginPage.tsx",
    "line": 76
  },
  {
    "route": "/admin/dashboard",
    "file": "src/features/admin/AdminLoginPage.tsx",
    "line": 96
  },
  {
    "route": "/admin/dashboard",
    "file": "src/features/admin/AdminRegisterPasskeyPage.tsx",
    "line": 60
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminRegisterPasskeyPage.tsx",
    "line": 25
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminRegisterPasskeyPage.tsx",
    "line": 40
  },
  {
    "route": "/cc/login",
    "file": "src/command-center/CommandCenterApp.tsx",
    "line": 44
  },
  {
    "route": "/cc/dossiers",
    "file": "src/command-center/pages/CCLogin.tsx",
    "line": 19
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/validations/ValidationsModule.tsx",
    "line": 171
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/validations/ValidationsModule.tsx",
    "line": 249
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/projects/ProjectsModule.tsx",
    "line": 91
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/leads/LeadsModule.tsx",
    "line": 212
  },
  {
    "route": "/cercles/profile/",
    "file": "src/command-center/modules/inscrits/InscritsModule.tsx",
    "line": 328
  },
  {
    "route": "/cc/dossiers",
    "file": "src/command-center/modules/dossiers/DossierDetail.tsx",
    "line": 370
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossierShadowView.tsx",
    "line": 180
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 233
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 237
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 238
  },
  {
    "route": "/simulateur",
    "file": "src/command-center/modules/dashboard/CCDashboard.tsx",
    "line": 58
  },
  {
    "route": "/cc/archive",
    "file": "src/command-center/modules/archive/ArchiveDossierView.tsx",
    "line": 83
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/archive/ArchiveDossierView.tsx",
    "line": 104
  },
  {
    "route": "/cc/archive/",
    "file": "src/command-center/modules/archive/ArchiveModule.tsx",
    "line": 243
  }
] as const;
export const UNKNOWN_ROUTE_USAGES = [
  {
    "route": "/cc",
    "file": "src/ui/simulateur/SimulatorPage.tsx",
    "line": 44
  },
  {
    "route": "/cercles",
    "file": "src/ui/landing/DoorsSection.tsx",
    "line": 62
  },
  {
    "route": "/creer-compte",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 752
  },
  {
    "route": "/cc",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 221
  },
  {
    "route": "/cc",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 241
  },
  {
    "route": "/cc",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 252
  },
  {
    "route": "/inscription",
    "file": "src/tomes/tome5/pages/AccountTypeChooser.tsx",
    "line": 31
  },
  {
    "route": "/creer-compte",
    "file": "src/tomes/tome5/pages/ClientSignup.tsx",
    "line": 114
  },
  {
    "route": "/mot-de-passe-oublie",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 184
  },
  {
    "route": "/cercles",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 39
  },
  {
    "route": "/cc/login",
    "file": "src/tomes/tome4/apiClient.ts",
    "line": 96
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 80
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 136
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 27
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 33
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 96
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 107
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 94
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 446
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 561
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 560
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p4/P4Home.tsx",
    "line": 212
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p4/P4Home.tsx",
    "line": 211
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p3/P3Home.tsx",
    "line": 216
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p3/P3Home.tsx",
    "line": 215
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 27
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 34
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 110
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 121
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 106
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 692
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 812
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 811
  },
  {
    "route": "/p1/dossier/phases",
    "file": "src/tomes/tome3/portals/p1/P1Dossier.tsx",
    "line": 67
  },
  {
    "route": "/p1/dossier/phases",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 140
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 143
  },
  {
    "route": "/verify-phone",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 168
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 48
  },
  {
    "route": "/cc/dashboard",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 88
  },
  {
    "route": "/cc/dashboard",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 128
  },
  {
    "route": "/admin/login",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 143
  },
  {
    "route": "/cercles",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 202
  },
  {
    "route": "/cercles/me/profile",
    "file": "src/features/cercles/AnnuairePage.tsx",
    "line": 127
  },
  {
    "route": "/cercles/profile/",
    "file": "src/features/cercles/AnnuairePage.tsx",
    "line": 135
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/AssociationApplyPage.tsx",
    "line": 136
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 130
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 135
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 141
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 149
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 230
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 451
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 452
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 34
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 38
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 59
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 62
  },
  {
    "route": "/cercles/snasp-architectes-prive/rejoindre",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 93
  },
  {
    "route": "/cercles/anjaum-jeunes-architectes/rejoindre",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 112
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 196
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 199
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 215
  },
  {
    "route": "/cercles/nouveau",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 134
  },
  {
    "route": "/cercles/messages",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 137
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 145
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 148
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 183
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 199
  },
  {
    "route": "/cercles/messages",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 93
  },
  {
    "route": "/cercles/messages/",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 89
  },
  {
    "route": "/cercles/profile/",
    "file": "src/features/cercles/EditProfilePage.tsx",
    "line": 194
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 219
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 291
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 134
  },
  {
    "route": "/post/",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 233
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 234
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 58
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 65
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 102
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 108
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 121
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/NewCerclePage.tsx",
    "line": 83
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/NewCerclePage.tsx",
    "line": 24
  },
  {
    "route": "/cercles/me/edit",
    "file": "src/features/cercles/ProfilePage.tsx",
    "line": 183
  },
  {
    "route": "/cercles/messages/new/",
    "file": "src/features/cercles/ProfilePage.tsx",
    "line": 188
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 59
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 72
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 145
  },
  {
    "route": "/cercles/marketplace/photos",
    "file": "src/features/cercles/marketplace/MarketplacePage.tsx",
    "line": 57
  },
  {
    "route": "/cercles/mes-offres",
    "file": "src/features/cercles/marketplace/MarketplacePage.tsx",
    "line": 58
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/marketplace/MarketplacePhotosPage.tsx",
    "line": 69
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/marketplace/MyOffersPage.tsx",
    "line": 65
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/marketplace/ProductDetailPage.tsx",
    "line": 36
  },
  {
    "route": "/cercles/mes-offres",
    "file": "src/features/cercles/marketplace/ProductDetailPage.tsx",
    "line": 69
  },
  {
    "route": "/cercles/messages/new/",
    "file": "src/features/cercles/marketplace/ProductDetailPage.tsx",
    "line": 95
  },
  {
    "route": "/admin/users",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 70
  },
  {
    "route": "/admin/cercles",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 71
  },
  {
    "route": "/admin/audit",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 72
  },
  {
    "route": "/admin/admins",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 73
  },
  {
    "route": "/admin/security",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 74
  },
  {
    "route": "/admin/audit",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 131
  },
  {
    "route": "/admin/users",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 171
  },
  {
    "route": "/admin/security/webauthn",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 175
  },
  {
    "route": "/admin/security/ips",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 179
  },
  {
    "route": "/admin/admins/new",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 184
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 27
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 43
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 53
  },
  {
    "route": "/admin/dashboard",
    "file": "src/features/admin/AdminLoginPage.tsx",
    "line": 36
  },
  {
    "route": "/admin/security/webauthn",
    "file": "src/features/admin/AdminLoginPage.tsx",
    "line": 76
  },
  {
    "route": "/admin/dashboard",
    "file": "src/features/admin/AdminLoginPage.tsx",
    "line": 96
  },
  {
    "route": "/admin/dashboard",
    "file": "src/features/admin/AdminRegisterPasskeyPage.tsx",
    "line": 60
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminRegisterPasskeyPage.tsx",
    "line": 25
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminRegisterPasskeyPage.tsx",
    "line": 40
  },
  {
    "route": "/cc/login",
    "file": "src/command-center/CommandCenterApp.tsx",
    "line": 44
  },
  {
    "route": "/cc/dossiers",
    "file": "src/command-center/pages/CCLogin.tsx",
    "line": 19
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/validations/ValidationsModule.tsx",
    "line": 171
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/validations/ValidationsModule.tsx",
    "line": 249
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/projects/ProjectsModule.tsx",
    "line": 91
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/leads/LeadsModule.tsx",
    "line": 212
  },
  {
    "route": "/cercles/profile/",
    "file": "src/command-center/modules/inscrits/InscritsModule.tsx",
    "line": 328
  },
  {
    "route": "/cc/dossiers",
    "file": "src/command-center/modules/dossiers/DossierDetail.tsx",
    "line": 370
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossierShadowView.tsx",
    "line": 180
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 233
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 237
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 238
  },
  {
    "route": "/simulateur",
    "file": "src/command-center/modules/dashboard/CCDashboard.tsx",
    "line": 58
  },
  {
    "route": "/cc/archive",
    "file": "src/command-center/modules/archive/ArchiveDossierView.tsx",
    "line": 83
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/archive/ArchiveDossierView.tsx",
    "line": 104
  },
  {
    "route": "/cc/archive/",
    "file": "src/command-center/modules/archive/ArchiveModule.tsx",
    "line": 243
  }
] as const;
export const UNUSED_DECLARED_ROUTES = [
  "/auth/signup",
  "/p1/confirmation",
  "/p1/qualification",
  "/p1/offres",
  "/p1/packs-personnalise",
  "/p2/form",
  "/p2/result",
  "/enterprise/api"
] as const;
export const DEAD_CTA_HINTS = [
  {
    "kind": "href_hash",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 741,
    "snippet": "')\">VVIP</div> <a class=\"pill\" href=\"#\" onclick=\"soon('Panier activé après tunnel de commande');return false;\">"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 682,
    "snippet": "itrine)\"> <button type=\"button\" onclick=\"window.open('https://web.facebook.com/yassineattarassi','_blank')\">f</b"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 683,
    "snippet": "</button> <button type=\"button\" onclick=\"window.open('https://www.instagram.com/arc_bati_architecture','_blank')"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 684,
    "snippet": "</button> <button type=\"button\" onclick=\"soon('LinkedIn — bientôt disponible')\">in</button> <button type"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 685,
    "snippet": "</button> <button type=\"button\" onclick=\"soon('TikTok @arc_bati_architecture — bientôt')\">tt</button> </di"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 688,
    "snippet": "> </div> <div class=\"chip\" onclick=\"window.location.href='/p1'\">Concevoir</div> <div class=\"chip\" onc"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 689,
    "snippet": "Concevoir</div> <div class=\"chip\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20cl%C3"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 690,
    "snippet": "é en main</div> <div class=\"chip\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20fonci"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 707,
    "snippet": "role=\"menu\"> <a href=\"/p1\" onclick=\"window.location.href='/p1';return false;\"> <strong>Projet"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 711,
    "snippet": "</a> <a href=\"/p2\" onclick=\"window.location.href='/p2';return false;\"> <strong>Projet"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 715,
    "snippet": "</a> <a href=\"/p3\" onclick=\"window.location.href='/p3';return false;\"> <strong>Réalis"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 719,
    "snippet": "</a> <a href=\"/p4\" onclick=\"window.location.href='/p4';return false;\"> <strong>Invest"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 723,
    "snippet": "</a> <a href=\"/p5\" onclick=\"window.location.href='/p5';return false;\"> <strong>Rappor"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 727,
    "snippet": "</a> <a href=\"/p6\" onclick=\"window.location.href='/p6';return false;\"> <strong>Entrep"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 735,
    "snippet": "<a class=\"pill\" href=\"#medias\" onclick=\"scrollToId('medias');return false;\">Médias</a> <!-- Vente abo"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 738,
    "snippet": "vice) --> <div class=\"pill vip\" onclick=\"openSubModal('vip')\">VIP</div> <div class=\"pill vvip\" onclick=\""
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 739,
    "snippet": "IP</div> <div class=\"pill vvip\" onclick=\"openSubModal('vvip')\">VVIP</div> <a class=\"pill\" href=\"#\" oncl"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 741,
    "snippet": "/div> <a class=\"pill\" href=\"#\" onclick=\"soon('Panier activé après tunnel de commande');return false;\">Panier</a"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 745,
    "snippet": "<button class=\"lang-btn active\" onclick=\"setLang('fr')\">FR</button> <button class=\"lang-btn\" onclick=\""
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 746,
    "snippet": "ton> <button class=\"lang-btn\" onclick=\"setLang('ar')\">AR</button> <button class=\"lang-btn\" onclick=\""
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 747,
    "snippet": "ton> <button class=\"lang-btn\" onclick=\"setLang('en')\">EN</button> </div> <!-- AUTH BUTTONS --"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 771,
    "snippet": "tsApp) --> <article class=\"cat\" onclick=\"window.location.href='/p1'\"> <h3>Projet personnel / familial<"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 777,
    "snippet": "/article> <article class=\"cat\" onclick=\"window.location.href='/p2'\"> <h3>Projet immobilier & équipeme"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 783,
    "snippet": "/article> <article class=\"cat\" onclick=\"window.location.href='/p3'\"> <h3>Réalisation clé en main</h3>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 789,
    "snippet": "/article> <article class=\"cat\" onclick=\"window.location.href='/p4'\"> <h3>Investisseur & foncier</h3>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 795,
    "snippet": "/article> <article class=\"cat\" onclick=\"window.location.href='/p5'\"> <h3>Rapports & expertises</h3>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 801,
    "snippet": "/article> <article class=\"cat\" onclick=\"window.location.href='/p6'\"> <h3>Entreprise / partenaire</h3>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 835,
    "snippet": "elect> <button type=\"button\" onclick=\"autoOrient()\">Être orienté vers la bonne catégorie</button> </d"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 848,
    "snippet": "on class=\"mbtn secondary\" type=\"button\" onclick=\"soon('Démo vidéo sera disponible en lecture interne.')\">Voir</button>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 849,
    "snippet": "tton class=\"mbtn primary\" type=\"button\" onclick=\"scrollToId('medias')\">Aller aux Médias</button> </div> </"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 862,
    "snippet": "on class=\"mbtn secondary\" type=\"button\" onclick=\"openSubModal('vip')\">VIP</button> <button class=\"mbtn primary"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 863,
    "snippet": "tton class=\"mbtn primary\" type=\"button\" onclick=\"openSubModal('vvip')\">VVIP</button> </div> </div> </a"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 880,
    "snippet": "oppScroller\"> <div class=\"tile\" onclick=\"soon('Détail opportunité: visible dans Médias / VIP selon type.');\">"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 892,
    "snippet": "</div> <div class=\"tile\" onclick=\"soon('Détail opportunité: visible dans Médias / VIP selon type.');\">"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 904,
    "snippet": "</div> <div class=\"tile\" onclick=\"soon('Bientôt.');\"> <div class=\"thumb\"> <div clas"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 955,
    "snippet": "nt --> <div class=\"modal\" id=\"subModal\" onclick=\"modalBackdropClose(event,'subModal')\"> <div class=\"modal-card\" role=\""
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 959,
    "snippet": "span> <button class=\"modal-close\" onclick=\"closeModal('subModal')\">Retour</button> </div> <div class=\"moda"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 970,
    "snippet": "\"> <button class=\"mbtn primary\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20je%20"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 971,
    "snippet": "<button class=\"mbtn secondary\" onclick=\"closeModal('subModal')\">Plus tard</button> </div> </div> </"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 978,
    "snippet": ") --> <div class=\"modal\" id=\"leadModal\" onclick=\"modalBackdropClose(event,'leadModal')\"> <div class=\"modal-card\" role="
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 982,
    "snippet": "span> <button class=\"modal-close\" onclick=\"closeModal('leadModal')\">Retour</button> </div> <div class=\"mod"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1005,
    "snippet": "\"> <button class=\"mbtn primary\" onclick=\"submitLead()\">Envoyer via plateforme</button> <button class=\"mb"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1006,
    "snippet": "<button class=\"mbtn secondary\" onclick=\"closeModal('leadModal')\">Annuler</button> </div> </div> </d"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1016,
    "snippet": "--> <div class=\"modal\" id=\"submitModal\" onclick=\"modalBackdropClose(event,'submitModal')\"> <div class=\"modal-card\" sty"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1020,
    "snippet": "span> <button class=\"modal-close\" onclick=\"closeModal('submitModal')\">Retour</button> </div> <div class=\"m"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1058,
    "snippet": "\"> <button class=\"mbtn primary\" onclick=\"submitArticle()\" style=\"flex:1;\">Envoyer pour mod&eacute;ration</button"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1059,
    "snippet": "<button class=\"mbtn secondary\" onclick=\"closeModal('submitModal')\">Annuler</button> </div> <p style"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1078,
    "snippet": "{ // Minimal global helpers used by onclick=\"...\" in the injected HTML. ensureGlobal(\"openModal\", (id: string) ="
  },
  {
    "kind": "href_hash",
    "file": "src/ui/dev/DevRoutesPage.tsx",
    "line": 93,
    "snippet": "liste des patterns à risque (ex: <code>href=\"#\"</code>, inline <code>onclick</code>). Ce n’est pas une preuve qu’un bou"
  }
] as const;
