/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 * Generated by scripts/generate-route-audit.mjs
 */
export const DECLARED_ROUTES = [
  "/auth/login",
  "/auth/signup",
  "/p1/config",
  "/p1/confirmation",
  "/p1/qualification",
  "/p1/qualify",
  "/p1/offres",
  "/p1/packs-personnalise",
  "/media",
  "/p2",
  "/p2/form",
  "/p2/result",
  "/p3",
  "/p4",
  "/p5",
  "/p6",
  "/enterprise/api",
  "/forbidden",
  "/upgrade",
  "/faq",
  "/",
  "/login",
  "/p1",
  "/p1/packs",
  "/p1/dossier",
  "/_dev/routes",
  "/terriscan"
] as const;
export const ROUTE_USAGES = [
  {
    "route": "/cc",
    "file": "src/ui/simulateur/SimulatorPage.tsx",
    "line": 44
  },
  {
    "route": "/login",
    "file": "src/ui/landing/CTASection.tsx",
    "line": 28
  },
  {
    "route": "/cercles",
    "file": "src/ui/landing/DoorsSection.tsx",
    "line": 64
  },
  {
    "route": "/",
    "file": "src/ui/landing/DoorsSection.tsx",
    "line": 67
  },
  {
    "route": "/login",
    "file": "src/ui/landing/FooterSection.tsx",
    "line": 36
  },
  {
    "route": "/login",
    "file": "src/ui/landing/FooterSection.tsx",
    "line": 37
  },
  {
    "route": "/media",
    "file": "src/ui/landing/FooterSection.tsx",
    "line": 55
  },
  {
    "route": "/login",
    "file": "src/ui/landing/HeroSection.tsx",
    "line": 47
  },
  {
    "route": "/login",
    "file": "src/ui/landing/HeroSection.tsx",
    "line": 115
  },
  {
    "route": "/p1",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 729
  },
  {
    "route": "/p1",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 748
  },
  {
    "route": "/p2",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 752
  },
  {
    "route": "/p3",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 756
  },
  {
    "route": "/p4",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 760
  },
  {
    "route": "/p5",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 764
  },
  {
    "route": "/p6",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 768
  },
  {
    "route": "/login",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 792
  },
  {
    "route": "/creer-compte",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 793
  },
  {
    "route": "/p1",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 810
  },
  {
    "route": "/p2",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 816
  },
  {
    "route": "/p3",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 822
  },
  {
    "route": "/p4",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 828
  },
  {
    "route": "/p5",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 834
  },
  {
    "route": "/p6",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 840
  },
  {
    "route": "/media",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1271
  },
  {
    "route": "/media",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1285
  },
  {
    "route": "/cc",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 221
  },
  {
    "route": "/p1",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 225
  },
  {
    "route": "/p2",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 226
  },
  {
    "route": "/p3",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 227
  },
  {
    "route": "/p4",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 228
  },
  {
    "route": "/p5",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 229
  },
  {
    "route": "/p6",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 230
  },
  {
    "route": "/cc",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 241
  },
  {
    "route": "/cc",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 252
  },
  {
    "route": "/",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 311
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/guards.tsx",
    "line": 10
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/guards.tsx",
    "line": 18
  },
  {
    "route": "/forbidden",
    "file": "src/tomes/tome5/guards.tsx",
    "line": 19
  },
  {
    "route": "/upgrade",
    "file": "src/tomes/tome5/guards.tsx",
    "line": 27
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/AccountTypeChooser.tsx",
    "line": 27
  },
  {
    "route": "/inscription",
    "file": "src/tomes/tome5/pages/AccountTypeChooser.tsx",
    "line": 33
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/AccountTypeChooser.tsx",
    "line": 53
  },
  {
    "route": "/creer-compte",
    "file": "src/tomes/tome5/pages/ClientSignup.tsx",
    "line": 116
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/ClientSignup.tsx",
    "line": 213
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/Forbidden.tsx",
    "line": 15
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/Forbidden.tsx",
    "line": 16
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/ForgotPassword.tsx",
    "line": 89
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/ForgotPassword.tsx",
    "line": 148
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 195
  },
  {
    "route": "/mot-de-passe-oublie",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 252
  },
  {
    "route": "/cercles",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 41
  },
  {
    "route": "/p1/packs",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 46
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/Signup.tsx",
    "line": 153
  },
  {
    "route": "/auth/login",
    "file": "src/tomes/tome5/pages/Signup.tsx",
    "line": 224
  },
  {
    "route": "/p1/packs",
    "file": "src/tomes/tome5/pages/Signup.tsx",
    "line": 32
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome5/pages/SignupSMS.tsx",
    "line": 29
  },
  {
    "route": "/auth/login",
    "file": "src/tomes/tome5/pages/SignupSMS.tsx",
    "line": 331
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/Upgrade.tsx",
    "line": 15
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/Upgrade.tsx",
    "line": 16
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome5/components/ClientProfileBanner.tsx",
    "line": 62
  },
  {
    "route": "/cc/login",
    "file": "src/tomes/tome4/apiClient.ts",
    "line": 96
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 129
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 176
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 337
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 338
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 359
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 177
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 358
  },
  {
    "route": "/login",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 75
  },
  {
    "route": "/p6",
    "file": "src/tomes/tome3/portals/p6/P6Dashboard.tsx",
    "line": 169
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/p6/P6Home.tsx",
    "line": 234
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 49
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 55
  },
  {
    "route": "/p5",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 62
  },
  {
    "route": "/p5",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 184
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 185
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 214
  },
  {
    "route": "/sig",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 215
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 501
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 212
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 499
  },
  {
    "route": "/p5/finalize",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 576
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 570
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 665
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 666
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 664
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p4/P4Home.tsx",
    "line": 234
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/p4/P4Home.tsx",
    "line": 235
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p4/P4Home.tsx",
    "line": 233
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p3/P3Home.tsx",
    "line": 232
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/p3/P3Home.tsx",
    "line": 233
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p3/P3Home.tsx",
    "line": 231
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 27
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 34
  },
  {
    "route": "/p2",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 41
  },
  {
    "route": "/p5",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 70
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 110
  },
  {
    "route": "/p2",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 120
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 121
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 106
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 663
  },
  {
    "route": "/p5",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 694
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 774
  },
  {
    "route": "/",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 775
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 1187
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 773
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1ClientPhases.tsx",
    "line": 146
  },
  {
    "route": "/dossier/",
    "file": "src/tomes/tome3/portals/p1/P1Dashboard.tsx",
    "line": 566
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1Dossier.tsx",
    "line": 51
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1Dossier.tsx",
    "line": 48
  },
  {
    "route": "/p1/dossier/phases",
    "file": "src/tomes/tome3/portals/p1/P1Dossier.tsx",
    "line": 69
  },
  {
    "route": "/p1/packs",
    "file": "src/tomes/tome3/portals/p1/P1Landing.tsx",
    "line": 1006
  },
  {
    "route": "/auth/login",
    "file": "src/tomes/tome3/portals/p1/P1Landing.tsx",
    "line": 2277
  },
  {
    "route": "/login",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 67
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 84
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 101
  },
  {
    "route": "/p1/dossier",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 137
  },
  {
    "route": "/p1/dossier/phases",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 140
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 143
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1OffersAndTunnel.tsx",
    "line": 37
  },
  {
    "route": "/login",
    "file": "src/tomes/tome3/portals/p1/P1OffersAndTunnel.tsx",
    "line": 43
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 621
  },
  {
    "route": "/login",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 166
  },
  {
    "route": "/verify-phone",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 170
  },
  {
    "route": "/p1/dossier",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 357
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 41
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 49
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 58
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 63
  },
  {
    "route": "/p1/config",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 133
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 241
  },
  {
    "route": "/faq",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 495
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 44
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 49
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 51
  },
  {
    "route": "/login",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 53
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 91
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 200
  },
  {
    "route": "/cc/dashboard",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 138
  },
  {
    "route": "/sig",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 144
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 172
  },
  {
    "route": "/cc/dashboard",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 185
  },
  {
    "route": "/sig",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 188
  },
  {
    "route": "/sig",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 202
  },
  {
    "route": "/admin/login",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 218
  },
  {
    "route": "/cercles",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 285
  },
  {
    "route": "/p2/dossier/",
    "file": "src/features/pv-commission/PvCommissionDecisions.tsx",
    "line": 164
  },
  {
    "route": "/p2/dossier/",
    "file": "src/features/pv-commission/PvCommissionUpload.tsx",
    "line": 112
  },
  {
    "route": "/p2/dossier/",
    "file": "src/features/pv-commission/PvCommissionUpload.tsx",
    "line": 115
  },
  {
    "route": "/prestataires/tarifs/",
    "file": "src/features/prestataire-tarifs/PrestataireTarifsList.tsx",
    "line": 140
  },
  {
    "route": "/p6",
    "file": "src/features/prestataire-tarifs/TarifContractPublic.tsx",
    "line": 72
  },
  {
    "route": "/notifications",
    "file": "src/features/notifications/NotificationBell.tsx",
    "line": 150
  },
  {
    "route": "/notifications",
    "file": "src/features/notifications/NotificationPreferencesPage.tsx",
    "line": 117
  },
  {
    "route": "/parametres/notifications",
    "file": "src/features/notifications/NotificationsCenterPage.tsx",
    "line": 121
  },
  {
    "route": "/dossier/",
    "file": "src/features/mon-parcours/MonParcoursPage.tsx",
    "line": 218
  },
  {
    "route": "/media",
    "file": "src/features/media/ArticleDetailPage.tsx",
    "line": 103
  },
  {
    "route": "/media",
    "file": "src/features/media/ArticleDetailPage.tsx",
    "line": 122
  },
  {
    "route": "/login",
    "file": "src/features/media/components/ArticleCard.tsx",
    "line": 265
  },
  {
    "route": "/media",
    "file": "src/features/media/components/ArticleCard.tsx",
    "line": 215
  },
  {
    "route": "/materiaux",
    "file": "src/features/materials/MaterialDetail.tsx",
    "line": 72
  },
  {
    "route": "/materiaux",
    "file": "src/features/materials/MaterialDetail.tsx",
    "line": 112
  },
  {
    "route": "/p5",
    "file": "src/features/geo/SigExplorer.tsx",
    "line": 208
  },
  {
    "route": "/",
    "file": "src/features/geo/SigExplorer.tsx",
    "line": 215
  },
  {
    "route": "/dossiers/",
    "file": "src/features/dossier-phases/DossierPhaseDetailPage.tsx",
    "line": 73
  },
  {
    "route": "/dossiers/",
    "file": "src/features/dossier-phases/DossierPhaseDetailPage.tsx",
    "line": 91
  },
  {
    "route": "/login",
    "file": "src/features/dossier-phases/errorStates.tsx",
    "line": 92
  },
  {
    "route": "/dossier/",
    "file": "src/features/dossier-interactions/DossierMentionsPanel.tsx",
    "line": 5
  },
  {
    "route": "/login",
    "file": "src/features/cps-generator/DossierCpsPage.tsx",
    "line": 96
  },
  {
    "route": "/portal",
    "file": "src/features/cps-generator/DossierCpsPage.tsx",
    "line": 100
  },
  {
    "route": "/p1",
    "file": "src/features/cps-generator/DossierCpsPage.tsx",
    "line": 106
  },
  {
    "route": "/p2",
    "file": "src/features/cps-generator/DossierCpsPage.tsx",
    "line": 107
  },
  {
    "route": "/p3",
    "file": "src/features/cps-generator/DossierCpsPage.tsx",
    "line": 108
  },
  {
    "route": "/portal",
    "file": "src/features/cps-generator/DossierCpsPage.tsx",
    "line": 109
  },
  {
    "route": "/cercles/me/profile",
    "file": "src/features/cercles/AnnuairePage.tsx",
    "line": 174
  },
  {
    "route": "/cercles/profile/",
    "file": "src/features/cercles/AnnuairePage.tsx",
    "line": 182
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/AssociationApplyPage.tsx",
    "line": 136
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 132
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 137
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 143
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 151
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 232
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 456
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 457
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 50
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 53
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 54
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 72
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 75
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 76
  },
  {
    "route": "/cercles/snasp-architectes-prive/rejoindre",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 104
  },
  {
    "route": "/cercles/anjaum-jeunes-architectes/rejoindre",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 121
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 186
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 189
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 190
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 204
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 205
  },
  {
    "route": "/",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 108
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 54
  },
  {
    "route": "/p1",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 65
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 73
  },
  {
    "route": "/login",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 93
  },
  {
    "route": "/cercles/nouveau",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 139
  },
  {
    "route": "/cercles/messages",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 142
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 150
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 153
  },
  {
    "route": "/cercles/messages",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 208
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 183
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 199
  },
  {
    "route": "/cercles/messages",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 93
  },
  {
    "route": "/cercles/messages/",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 89
  },
  {
    "route": "/cercles/profile/",
    "file": "src/features/cercles/EditProfilePage.tsx",
    "line": 186
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 231
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 304
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 146
  },
  {
    "route": "/post/",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 246
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 247
  },
  {
    "route": "/",
    "file": "src/features/cercles/InscriptionPage.tsx",
    "line": 318
  },
  {
    "route": "/",
    "file": "src/features/cercles/InscriptionPage.tsx",
    "line": 573
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 58
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 65
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 102
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 108
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 121
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/NewCerclePage.tsx",
    "line": 83
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/NewCerclePage.tsx",
    "line": 24
  },
  {
    "route": "/cercles/me/edit",
    "file": "src/features/cercles/ProfilePage.tsx",
    "line": 184
  },
  {
    "route": "/cercles/messages/new/",
    "file": "src/features/cercles/ProfilePage.tsx",
    "line": 189
  },
  {
    "route": "/",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 50
  },
  {
    "route": "/login",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 58
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 59
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 72
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 145
  },
  {
    "route": "/login",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 146
  },
  {
    "route": "/cercles/marketplace/photos",
    "file": "src/features/cercles/marketplace/MarketplacePage.tsx",
    "line": 59
  },
  {
    "route": "/cercles/mes-offres",
    "file": "src/features/cercles/marketplace/MarketplacePage.tsx",
    "line": 60
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/marketplace/MarketplacePhotosPage.tsx",
    "line": 69
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/marketplace/MyOffersPage.tsx",
    "line": 65
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/marketplace/ProductDetailPage.tsx",
    "line": 36
  },
  {
    "route": "/cercles/mes-offres",
    "file": "src/features/cercles/marketplace/ProductDetailPage.tsx",
    "line": 69
  },
  {
    "route": "/cercles/messages/new/",
    "file": "src/features/cercles/marketplace/ProductDetailPage.tsx",
    "line": 95
  },
  {
    "route": "/cercles/me/edit",
    "file": "src/features/cabinet/CabinetManagePage.tsx",
    "line": 142
  },
  {
    "route": "/",
    "file": "src/features/cabinet/CabinetPublicPage.tsx",
    "line": 123
  },
  {
    "route": "/admin/users",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 70
  },
  {
    "route": "/admin/cercles",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 71
  },
  {
    "route": "/admin/audit",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 72
  },
  {
    "route": "/admin/admins",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 73
  },
  {
    "route": "/admin/security",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 74
  },
  {
    "route": "/admin/audit",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 131
  },
  {
    "route": "/admin/users",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 171
  },
  {
    "route": "/admin/security/webauthn",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 175
  },
  {
    "route": "/admin/security/ips",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 179
  },
  {
    "route": "/admin/admins/new",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 184
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 27
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 43
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 53
  },
  {
    "route": "/admin/dashboard",
    "file": "src/features/admin/AdminLoginPage.tsx",
    "line": 36
  },
  {
    "route": "/admin/security/webauthn",
    "file": "src/features/admin/AdminLoginPage.tsx",
    "line": 76
  },
  {
    "route": "/admin/dashboard",
    "file": "src/features/admin/AdminLoginPage.tsx",
    "line": 96
  },
  {
    "route": "/admin/dashboard",
    "file": "src/features/admin/AdminRegisterPasskeyPage.tsx",
    "line": 60
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminRegisterPasskeyPage.tsx",
    "line": 25
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminRegisterPasskeyPage.tsx",
    "line": 40
  },
  {
    "route": "/",
    "file": "src/components/error-boundary/ErrorPage.tsx",
    "line": 141
  },
  {
    "route": "/cc/login",
    "file": "src/command-center/CommandCenterApp.tsx",
    "line": 44
  },
  {
    "route": "/cc/dossiers",
    "file": "src/command-center/pages/CCLogin.tsx",
    "line": 19
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/validations/ValidationsModule.tsx",
    "line": 171
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/validations/ValidationsModule.tsx",
    "line": 249
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/projects/ProjectsModule.tsx",
    "line": 91
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/leads/LeadsModule.tsx",
    "line": 243
  },
  {
    "route": "/cercles/profile/",
    "file": "src/command-center/modules/inscrits/InscritsModule.tsx",
    "line": 328
  },
  {
    "route": "/cc/dossiers",
    "file": "src/command-center/modules/dossiers/DossierDetail.tsx",
    "line": 370
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossierShadowView.tsx",
    "line": 180
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 240
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 243
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 276
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 280
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 281
  },
  {
    "route": "/simulateur",
    "file": "src/command-center/modules/dashboard/CCDashboard.tsx",
    "line": 58
  },
  {
    "route": "/cc/archive",
    "file": "src/command-center/modules/archive/ArchiveDossierView.tsx",
    "line": 83
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/archive/ArchiveDossierView.tsx",
    "line": 104
  },
  {
    "route": "/cc/archive/",
    "file": "src/command-center/modules/archive/ArchiveModule.tsx",
    "line": 243
  }
] as const;
export const UNKNOWN_ROUTE_USAGES = [
  {
    "route": "/cc",
    "file": "src/ui/simulateur/SimulatorPage.tsx",
    "line": 44
  },
  {
    "route": "/cercles",
    "file": "src/ui/landing/DoorsSection.tsx",
    "line": 64
  },
  {
    "route": "/creer-compte",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 793
  },
  {
    "route": "/cc",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 221
  },
  {
    "route": "/cc",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 241
  },
  {
    "route": "/cc",
    "file": "src/ui/docs/DocsPage.tsx",
    "line": 252
  },
  {
    "route": "/inscription",
    "file": "src/tomes/tome5/pages/AccountTypeChooser.tsx",
    "line": 33
  },
  {
    "route": "/creer-compte",
    "file": "src/tomes/tome5/pages/ClientSignup.tsx",
    "line": 116
  },
  {
    "route": "/mot-de-passe-oublie",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 252
  },
  {
    "route": "/cercles",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 41
  },
  {
    "route": "/cc/login",
    "file": "src/tomes/tome4/apiClient.ts",
    "line": 96
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 129
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 176
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 337
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 359
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 177
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/payment/PaymentPages.tsx",
    "line": 358
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 49
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 55
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 185
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 214
  },
  {
    "route": "/sig",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 215
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 501
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 212
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p5/P5Finalize.tsx",
    "line": 499
  },
  {
    "route": "/p5/finalize",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 576
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 570
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 665
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p5/P5Home.tsx",
    "line": 664
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p4/P4Home.tsx",
    "line": 234
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p4/P4Home.tsx",
    "line": 233
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p3/P3Home.tsx",
    "line": 232
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p3/P3Home.tsx",
    "line": 231
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 27
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 34
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 110
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 121
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p2/P2Finalize.tsx",
    "line": 106
  },
  {
    "route": "/creer-compte/client",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 663
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 774
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p2/P2Home.tsx",
    "line": 773
  },
  {
    "route": "/dossier/",
    "file": "src/tomes/tome3/portals/p1/P1Dashboard.tsx",
    "line": 566
  },
  {
    "route": "/p1/dossier/phases",
    "file": "src/tomes/tome3/portals/p1/P1Dossier.tsx",
    "line": 69
  },
  {
    "route": "/p1/dossier/phases",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 140
  },
  {
    "route": "/payment/start",
    "file": "src/tomes/tome3/portals/p1/P1MyDossiers.tsx",
    "line": 143
  },
  {
    "route": "/verify-phone",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 170
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 51
  },
  {
    "route": "/cc/dashboard",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 138
  },
  {
    "route": "/sig",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 144
  },
  {
    "route": "/cc/dashboard",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 185
  },
  {
    "route": "/sig",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 188
  },
  {
    "route": "/sig",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 202
  },
  {
    "route": "/admin/login",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 218
  },
  {
    "route": "/cercles",
    "file": "src/tomes/tome1/router/routes.tsx",
    "line": 285
  },
  {
    "route": "/p2/dossier/",
    "file": "src/features/pv-commission/PvCommissionDecisions.tsx",
    "line": 164
  },
  {
    "route": "/p2/dossier/",
    "file": "src/features/pv-commission/PvCommissionUpload.tsx",
    "line": 112
  },
  {
    "route": "/p2/dossier/",
    "file": "src/features/pv-commission/PvCommissionUpload.tsx",
    "line": 115
  },
  {
    "route": "/prestataires/tarifs/",
    "file": "src/features/prestataire-tarifs/PrestataireTarifsList.tsx",
    "line": 140
  },
  {
    "route": "/notifications",
    "file": "src/features/notifications/NotificationBell.tsx",
    "line": 150
  },
  {
    "route": "/notifications",
    "file": "src/features/notifications/NotificationPreferencesPage.tsx",
    "line": 117
  },
  {
    "route": "/parametres/notifications",
    "file": "src/features/notifications/NotificationsCenterPage.tsx",
    "line": 121
  },
  {
    "route": "/dossier/",
    "file": "src/features/mon-parcours/MonParcoursPage.tsx",
    "line": 218
  },
  {
    "route": "/materiaux",
    "file": "src/features/materials/MaterialDetail.tsx",
    "line": 72
  },
  {
    "route": "/materiaux",
    "file": "src/features/materials/MaterialDetail.tsx",
    "line": 112
  },
  {
    "route": "/dossiers/",
    "file": "src/features/dossier-phases/DossierPhaseDetailPage.tsx",
    "line": 73
  },
  {
    "route": "/dossiers/",
    "file": "src/features/dossier-phases/DossierPhaseDetailPage.tsx",
    "line": 91
  },
  {
    "route": "/dossier/",
    "file": "src/features/dossier-interactions/DossierMentionsPanel.tsx",
    "line": 5
  },
  {
    "route": "/portal",
    "file": "src/features/cps-generator/DossierCpsPage.tsx",
    "line": 100
  },
  {
    "route": "/portal",
    "file": "src/features/cps-generator/DossierCpsPage.tsx",
    "line": 109
  },
  {
    "route": "/cercles/me/profile",
    "file": "src/features/cercles/AnnuairePage.tsx",
    "line": 174
  },
  {
    "route": "/cercles/profile/",
    "file": "src/features/cercles/AnnuairePage.tsx",
    "line": 182
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/AssociationApplyPage.tsx",
    "line": 136
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 132
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 137
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 143
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 151
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 232
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 456
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/CercleDetailPage.tsx",
    "line": 457
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 50
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 54
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 72
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 75
  },
  {
    "route": "/cercles/snasp-architectes-prive/rejoindre",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 104
  },
  {
    "route": "/cercles/anjaum-jeunes-architectes/rejoindre",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 121
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 186
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 189
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/CerclesLanding.tsx",
    "line": 205
  },
  {
    "route": "/cercles/nouveau",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 139
  },
  {
    "route": "/cercles/messages",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 142
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 150
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 153
  },
  {
    "route": "/cercles/messages",
    "file": "src/features/cercles/CerclesShell.tsx",
    "line": 208
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 183
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 199
  },
  {
    "route": "/cercles/messages",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 93
  },
  {
    "route": "/cercles/messages/",
    "file": "src/features/cercles/DirectMessagesPage.tsx",
    "line": 89
  },
  {
    "route": "/cercles/profile/",
    "file": "src/features/cercles/EditProfilePage.tsx",
    "line": 186
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 231
  },
  {
    "route": "/cercles/annuaire",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 304
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 146
  },
  {
    "route": "/post/",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 246
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/FeedHomePage.tsx",
    "line": 247
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 58
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 65
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 102
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 108
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/LiveRoomPage.tsx",
    "line": 121
  },
  {
    "route": "/cercles",
    "file": "src/features/cercles/NewCerclePage.tsx",
    "line": 83
  },
  {
    "route": "/cercles/",
    "file": "src/features/cercles/NewCerclePage.tsx",
    "line": 24
  },
  {
    "route": "/cercles/me/edit",
    "file": "src/features/cercles/ProfilePage.tsx",
    "line": 184
  },
  {
    "route": "/cercles/messages/new/",
    "file": "src/features/cercles/ProfilePage.tsx",
    "line": 189
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 59
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 72
  },
  {
    "route": "/inscription",
    "file": "src/features/cercles/PublicPostPage.tsx",
    "line": 145
  },
  {
    "route": "/cercles/marketplace/photos",
    "file": "src/features/cercles/marketplace/MarketplacePage.tsx",
    "line": 59
  },
  {
    "route": "/cercles/mes-offres",
    "file": "src/features/cercles/marketplace/MarketplacePage.tsx",
    "line": 60
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/marketplace/MarketplacePhotosPage.tsx",
    "line": 69
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/marketplace/MyOffersPage.tsx",
    "line": 65
  },
  {
    "route": "/cercles/marketplace",
    "file": "src/features/cercles/marketplace/ProductDetailPage.tsx",
    "line": 36
  },
  {
    "route": "/cercles/mes-offres",
    "file": "src/features/cercles/marketplace/ProductDetailPage.tsx",
    "line": 69
  },
  {
    "route": "/cercles/messages/new/",
    "file": "src/features/cercles/marketplace/ProductDetailPage.tsx",
    "line": 95
  },
  {
    "route": "/cercles/me/edit",
    "file": "src/features/cabinet/CabinetManagePage.tsx",
    "line": 142
  },
  {
    "route": "/admin/users",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 70
  },
  {
    "route": "/admin/cercles",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 71
  },
  {
    "route": "/admin/audit",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 72
  },
  {
    "route": "/admin/admins",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 73
  },
  {
    "route": "/admin/security",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 74
  },
  {
    "route": "/admin/audit",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 131
  },
  {
    "route": "/admin/users",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 171
  },
  {
    "route": "/admin/security/webauthn",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 175
  },
  {
    "route": "/admin/security/ips",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 179
  },
  {
    "route": "/admin/admins/new",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 184
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 27
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 43
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminDashboard.tsx",
    "line": 53
  },
  {
    "route": "/admin/dashboard",
    "file": "src/features/admin/AdminLoginPage.tsx",
    "line": 36
  },
  {
    "route": "/admin/security/webauthn",
    "file": "src/features/admin/AdminLoginPage.tsx",
    "line": 76
  },
  {
    "route": "/admin/dashboard",
    "file": "src/features/admin/AdminLoginPage.tsx",
    "line": 96
  },
  {
    "route": "/admin/dashboard",
    "file": "src/features/admin/AdminRegisterPasskeyPage.tsx",
    "line": 60
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminRegisterPasskeyPage.tsx",
    "line": 25
  },
  {
    "route": "/admin/login",
    "file": "src/features/admin/AdminRegisterPasskeyPage.tsx",
    "line": 40
  },
  {
    "route": "/cc/login",
    "file": "src/command-center/CommandCenterApp.tsx",
    "line": 44
  },
  {
    "route": "/cc/dossiers",
    "file": "src/command-center/pages/CCLogin.tsx",
    "line": 19
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/validations/ValidationsModule.tsx",
    "line": 171
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/validations/ValidationsModule.tsx",
    "line": 249
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/projects/ProjectsModule.tsx",
    "line": 91
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/leads/LeadsModule.tsx",
    "line": 243
  },
  {
    "route": "/cercles/profile/",
    "file": "src/command-center/modules/inscrits/InscritsModule.tsx",
    "line": 328
  },
  {
    "route": "/cc/dossiers",
    "file": "src/command-center/modules/dossiers/DossierDetail.tsx",
    "line": 370
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossierShadowView.tsx",
    "line": 180
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 240
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 243
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 276
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 280
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 281
  },
  {
    "route": "/simulateur",
    "file": "src/command-center/modules/dashboard/CCDashboard.tsx",
    "line": 58
  },
  {
    "route": "/cc/archive",
    "file": "src/command-center/modules/archive/ArchiveDossierView.tsx",
    "line": 83
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/archive/ArchiveDossierView.tsx",
    "line": 104
  },
  {
    "route": "/cc/archive/",
    "file": "src/command-center/modules/archive/ArchiveModule.tsx",
    "line": 243
  }
] as const;
export const UNUSED_DECLARED_ROUTES = [
  "/auth/signup",
  "/p1/confirmation",
  "/p1/qualification",
  "/p1/offres",
  "/p1/packs-personnalise",
  "/p2/form",
  "/p2/result",
  "/enterprise/api",
  "/terriscan"
] as const;
export const DEAD_CTA_HINTS = [
  {
    "kind": "href_hash",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 782,
    "snippet": "\">VVIP</div> <a class=\"pill\" href=\"#\" onclick=\"soon('${attr(t(\"landing.nav.cart_soon\"))}');return false;\">${e"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 723,
    "snippet": "ia\"))}\"> <button type=\"button\" onclick=\"window.open('https://web.facebook.com/yassineattarassi','_blank')\">f</b"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 724,
    "snippet": "/button> <button type=\"button\" onclick=\"window.open('https://www.instagram.com/arc_bati_architecture','_blank')"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 725,
    "snippet": "/button> <button type=\"button\" onclick=\"soon('${attr(t(\"landing.alert.linkedin_soon\"))}')\">in</button>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 726,
    "snippet": "/button> <button type=\"button\" onclick=\"soon('${attr(t(\"landing.alert.tiktok_soon\"))}')\">tt</button> </d"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 729,
    "snippet": "</div> <div class=\"chip\" onclick=\"window.location.href='/p1'\">${esc(t(\"landing.chip.design\"))}</div>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 730,
    "snippet": "sign\"))}</div> <div class=\"chip\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20cl%C3"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 731,
    "snippet": "nkey\"))}</div> <div class=\"chip\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20fonci"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 748,
    "snippet": "role=\"menu\"> <a href=\"/p1\" onclick=\"window.location.href='/p1';return false;\"> <strong>${esc"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 752,
    "snippet": "</a> <a href=\"/p2\" onclick=\"window.location.href='/p2';return false;\"> <strong>${esc"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 756,
    "snippet": "</a> <a href=\"/p3\" onclick=\"window.location.href='/p3';return false;\"> <strong>${esc"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 760,
    "snippet": "</a> <a href=\"/p4\" onclick=\"window.location.href='/p4';return false;\"> <strong>${esc"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 764,
    "snippet": "</a> <a href=\"/p5\" onclick=\"window.location.href='/p5';return false;\"> <strong>${esc"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 768,
    "snippet": "</a> <a href=\"/p6\" onclick=\"window.location.href='/p6';return false;\"> <strong>${esc"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 776,
    "snippet": "<a class=\"pill\" href=\"#medias\" onclick=\"scrollToId('medias');return false;\">${esc(t(\"landing.nav.media\"))}</a>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 779,
    "snippet": "ice) --> <div class=\"pill vip\" onclick=\"openSubModal('vip')\">VIP</div> <div class=\"pill vvip\" onclick="
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 780,
    "snippet": "P</div> <div class=\"pill vvip\" onclick=\"openSubModal('vvip')\">VVIP</div> <a class=\"pill\" href=\"#\" on"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 782,
    "snippet": "iv> <a class=\"pill\" href=\"#\" onclick=\"soon('${attr(t(\"landing.nav.cart_soon\"))}');return false;\">${esc(t(\"lan"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 786,
    "snippet": "g-btn${lang === \"fr\" ? \" active\" : \"\"}\" onclick=\"setLang('fr')\">FR</button> <button class=\"lang-btn${lang ==="
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 787,
    "snippet": "g-btn${lang === \"ar\" ? \" active\" : \"\"}\" onclick=\"setLang('ar')\">AR</button> <button class=\"lang-btn${lang ==="
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 788,
    "snippet": "g-btn${lang === \"en\" ? \" active\" : \"\"}\" onclick=\"setLang('en')\">EN</button> </div> <!-- AUTH BUTTONS"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 810,
    "snippet": "sApp) --> <article class=\"cat\" onclick=\"window.location.href='/p1'\"> <h3>${esc(t(\"landing.cat.p1.tit"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 816,
    "snippet": "rticle> <article class=\"cat\" onclick=\"window.location.href='/p2'\"> <h3>${esc(t(\"landing.cat.p2.tit"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 822,
    "snippet": "rticle> <article class=\"cat\" onclick=\"window.location.href='/p3'\"> <h3>${esc(t(\"landing.cat.p3.tit"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 828,
    "snippet": "rticle> <article class=\"cat\" onclick=\"window.location.href='/p4'\"> <h3>${esc(t(\"landing.cat.p4.tit"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 834,
    "snippet": "rticle> <article class=\"cat\" onclick=\"window.location.href='/p5'\"> <h3>${esc(t(\"landing.cat.p5.tit"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 840,
    "snippet": "rticle> <article class=\"cat\" onclick=\"window.location.href='/p6'\"> <h3>${esc(t(\"landing.cat.p6.tit"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 874,
    "snippet": "ect> <button type=\"button\" onclick=\"autoOrient()\">${esc(t(\"landing.form.submit\"))}</button> </div>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 887,
    "snippet": "on class=\"mbtn secondary\" type=\"button\" onclick=\"soon('${attr(t(\"landing.aside.discover.soon\"))}')\">${esc(t(\"landing.asi"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 888,
    "snippet": "tton class=\"mbtn primary\" type=\"button\" onclick=\"scrollToId('medias')\">${esc(t(\"landing.aside.discover.goto\"))}</button>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 901,
    "snippet": "on class=\"mbtn secondary\" type=\"button\" onclick=\"openSubModal('vip')\">${esc(t(\"landing.aside.briefs.vip\"))}</button>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 902,
    "snippet": "tton class=\"mbtn primary\" type=\"button\" onclick=\"openSubModal('vvip')\">${esc(t(\"landing.aside.briefs.vvip\"))}</button>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 919,
    "snippet": "ppScroller\"> <div class=\"tile\" onclick=\"soon('${attr(t(\"landing.opp.detail_soon\"))}');\"> <div class="
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 931,
    "snippet": "</div> <div class=\"tile\" onclick=\"soon('${attr(t(\"landing.opp.detail_soon\"))}');\"> <div class="
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 943,
    "snippet": "</div> <div class=\"tile\" onclick=\"soon('${attr(t(\"landing.opp.soon\"))}');\"> <div class=\"thumb\""
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 997,
    "snippet": "t --> <div class=\"modal\" id=\"subModal\" onclick=\"modalBackdropClose(event,'subModal')\"> <div class=\"modal-card\" role="
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1001,
    "snippet": "pan> <button class=\"modal-close\" onclick=\"closeModal('subModal')\">${esc(t(\"landing.sub_modal.back\"))}</button>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1012,
    "snippet": "> <button class=\"mbtn primary\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20je%20"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1013,
    "snippet": "<button class=\"mbtn secondary\" onclick=\"closeModal('subModal')\">${esc(t(\"landing.sub_modal.later\"))}</button>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1020,
    "snippet": "--> <div class=\"modal\" id=\"leadModal\" onclick=\"modalBackdropClose(event,'leadModal')\"> <div class=\"modal-card\" role"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1024,
    "snippet": "pan> <button class=\"modal-close\" onclick=\"closeModal('leadModal')\">${esc(t(\"landing.sub_modal.back\"))}</button>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1047,
    "snippet": "> <button class=\"mbtn primary\" onclick=\"submitLead()\">${esc(t(\"landing.lead_modal.send\"))}</button> <b"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1048,
    "snippet": "<button class=\"mbtn secondary\" onclick=\"closeModal('leadModal')\">${esc(t(\"landing.lead_modal.cancel\"))}</button"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1058,
    "snippet": "-> <div class=\"modal\" id=\"submitModal\" onclick=\"modalBackdropClose(event,'submitModal')\"> <div class=\"modal-card\" st"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1062,
    "snippet": "pan> <button class=\"modal-close\" onclick=\"closeModal('submitModal')\">${esc(t(\"landing.submit_modal.back\"))}</butt"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1099,
    "snippet": "> <button class=\"mbtn primary\" onclick=\"submitArticle()\" style=\"flex:1;\">${esc(t(\"landing.submit_modal.send\"))}"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1100,
    "snippet": "<button class=\"mbtn secondary\" onclick=\"closeModal('submitModal')\">${esc(t(\"landing.submit_modal.cancel\"))}</bu"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1128,
    "snippet": "// Minimal global helpers used by onclick=\"...\" in the injected HTML. ensureGlobal(\"openModal\", (id: string)"
  },
  {
    "kind": "href_hash",
    "file": "src/ui/dev/DevRoutesPage.tsx",
    "line": 93,
    "snippet": "liste des patterns à risque (ex: <code>href=\"#\"</code>, inline <code>onclick</code>). Ce n’est pas une preuve qu’un bou"
  }
] as const;
