/**
 * AUTO-GENERATED FILE — DO NOT EDIT
 * Generated by scripts/generate-route-audit.mjs
 */
export const DECLARED_ROUTES = [
  "/auth/login",
  "/auth/signup",
  "/p1/config",
  "/p1/confirmation",
  "/p1/qualification",
  "/p1/qualify",
  "/p1/offres",
  "/p1/packs-personnalise",
  "/media",
  "/p2",
  "/p2/form",
  "/p2/result",
  "/p3",
  "/p4",
  "/p5",
  "/p6",
  "/enterprise/api",
  "/forbidden",
  "/upgrade",
  "/faq",
  "/",
  "/login",
  "/p1",
  "/p1/packs",
  "/p1/dossier",
  "/_dev/routes"
] as const;
export const ROUTE_USAGES = [
  {
    "route": "/cc",
    "file": "src/ui/simulateur/SimulatorPage.tsx",
    "line": 44
  },
  {
    "route": "/login",
    "file": "src/ui/landing/CTASection.tsx",
    "line": 26
  },
  {
    "route": "/",
    "file": "src/ui/landing/DoorsSection.tsx",
    "line": 62
  },
  {
    "route": "/login",
    "file": "src/ui/landing/FooterSection.tsx",
    "line": 34
  },
  {
    "route": "/login",
    "file": "src/ui/landing/FooterSection.tsx",
    "line": 35
  },
  {
    "route": "/media",
    "file": "src/ui/landing/FooterSection.tsx",
    "line": 53
  },
  {
    "route": "/login",
    "file": "src/ui/landing/HeroSection.tsx",
    "line": 45
  },
  {
    "route": "/login",
    "file": "src/ui/landing/HeroSection.tsx",
    "line": 115
  },
  {
    "route": "/p1",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 678
  },
  {
    "route": "/p1",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 697
  },
  {
    "route": "/login",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 741
  },
  {
    "route": "/login",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 742
  },
  {
    "route": "/p1",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 761
  },
  {
    "route": "/media",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1207
  },
  {
    "route": "/media",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1221
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/guards.tsx",
    "line": 10
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/guards.tsx",
    "line": 18
  },
  {
    "route": "/forbidden",
    "file": "src/tomes/tome5/guards.tsx",
    "line": 19
  },
  {
    "route": "/upgrade",
    "file": "src/tomes/tome5/guards.tsx",
    "line": 27
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/Forbidden.tsx",
    "line": 15
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/Forbidden.tsx",
    "line": 16
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 50
  },
  {
    "route": "/auth/signup",
    "file": "src/tomes/tome5/pages/Login.tsx",
    "line": 168
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/Signup.tsx",
    "line": 57
  },
  {
    "route": "/auth/login",
    "file": "src/tomes/tome5/pages/Signup.tsx",
    "line": 205
  },
  {
    "route": "/p1/packs",
    "file": "src/tomes/tome5/pages/Signup.tsx",
    "line": 30
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome5/pages/SignupSMS.tsx",
    "line": 29
  },
  {
    "route": "/auth/login",
    "file": "src/tomes/tome5/pages/SignupSMS.tsx",
    "line": 331
  },
  {
    "route": "/login",
    "file": "src/tomes/tome5/pages/Upgrade.tsx",
    "line": 15
  },
  {
    "route": "/",
    "file": "src/tomes/tome5/pages/Upgrade.tsx",
    "line": 16
  },
  {
    "route": "/cc/login",
    "file": "src/tomes/tome4/apiClient.ts",
    "line": 89
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1Dossier.tsx",
    "line": 49
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1Dossier.tsx",
    "line": 46
  },
  {
    "route": "/p1/packs",
    "file": "src/tomes/tome3/portals/p1/P1Landing.tsx",
    "line": 878
  },
  {
    "route": "/auth/login",
    "file": "src/tomes/tome3/portals/p1/P1Landing.tsx",
    "line": 2144
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1OffersAndTunnel.tsx",
    "line": 37
  },
  {
    "route": "/login",
    "file": "src/tomes/tome3/portals/p1/P1OffersAndTunnel.tsx",
    "line": 43
  },
  {
    "route": "/p1",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 615
  },
  {
    "route": "/login",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 164
  },
  {
    "route": "/verify-phone",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 168
  },
  {
    "route": "/p1/dossier",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 355
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 41
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 49
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 58
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 63
  },
  {
    "route": "/p1/config",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 133
  },
  {
    "route": "/p1/qualify",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 241
  },
  {
    "route": "/faq",
    "file": "src/tomes/tome3/portals/p1/P1PacksPersonnalise.tsx",
    "line": 495
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 16
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 20
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 22
  },
  {
    "route": "/login",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 24
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 69
  },
  {
    "route": "/",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 142
  },
  {
    "route": "/login",
    "file": "src/features/media/components/ArticleCard.tsx",
    "line": 263
  },
  {
    "route": "/media",
    "file": "src/features/media/components/ArticleCard.tsx",
    "line": 213
  },
  {
    "route": "/cc/login",
    "file": "src/command-center/CommandCenterApp.tsx",
    "line": 38
  },
  {
    "route": "/cc/dossiers",
    "file": "src/command-center/pages/CCLogin.tsx",
    "line": 19
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/projects/ProjectsModule.tsx",
    "line": 91
  },
  {
    "route": "/cc/dossiers",
    "file": "src/command-center/modules/dossiers/DossierDetail.tsx",
    "line": 369
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 172
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 176
  },
  {
    "route": "/simulateur",
    "file": "src/command-center/modules/dashboard/CCDashboard.tsx",
    "line": 55
  }
] as const;
export const UNKNOWN_ROUTE_USAGES = [
  {
    "route": "/cc",
    "file": "src/ui/simulateur/SimulatorPage.tsx",
    "line": 44
  },
  {
    "route": "/cc/login",
    "file": "src/tomes/tome4/apiClient.ts",
    "line": 89
  },
  {
    "route": "/verify-phone",
    "file": "src/tomes/tome3/portals/p1/P1Packs.tsx",
    "line": 168
  },
  {
    "route": "/portal",
    "file": "src/tomes/tome1/router/layouts.tsx",
    "line": 22
  },
  {
    "route": "/cc/login",
    "file": "src/command-center/CommandCenterApp.tsx",
    "line": 38
  },
  {
    "route": "/cc/dossiers",
    "file": "src/command-center/pages/CCLogin.tsx",
    "line": 19
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/projects/ProjectsModule.tsx",
    "line": 91
  },
  {
    "route": "/cc/dossiers",
    "file": "src/command-center/modules/dossiers/DossierDetail.tsx",
    "line": 369
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 172
  },
  {
    "route": "/cc/dossiers/",
    "file": "src/command-center/modules/dossiers/DossiersModule.tsx",
    "line": 176
  },
  {
    "route": "/simulateur",
    "file": "src/command-center/modules/dashboard/CCDashboard.tsx",
    "line": 55
  }
] as const;
export const UNUSED_DECLARED_ROUTES = [
  "/p1/confirmation",
  "/p1/qualification",
  "/p1/offres",
  "/p1/packs-personnalise",
  "/p2",
  "/p2/form",
  "/p2/result",
  "/p3",
  "/p4",
  "/p5",
  "/p6",
  "/enterprise/api"
] as const;
export const DEAD_CTA_HINTS = [
  {
    "kind": "href_hash",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 701,
    "snippet": "/small> </a> <a href=\"#\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2"
  },
  {
    "kind": "href_hash",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 705,
    "snippet": "/small> </a> <a href=\"#\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2"
  },
  {
    "kind": "href_hash",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 709,
    "snippet": "/small> </a> <a href=\"#\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2"
  },
  {
    "kind": "href_hash",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 713,
    "snippet": "/small> </a> <a href=\"#\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2"
  },
  {
    "kind": "href_hash",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 717,
    "snippet": "/small> </a> <a href=\"#\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2"
  },
  {
    "kind": "href_hash",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 731,
    "snippet": "')\">VVIP</div> <a class=\"pill\" href=\"#\" onclick=\"soon('Panier activé après tunnel de commande');return false;\">"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 672,
    "snippet": "itrine)\"> <button type=\"button\" onclick=\"window.open('https://web.facebook.com/yassineattarassi','_blank')\">f</b"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 673,
    "snippet": "</button> <button type=\"button\" onclick=\"window.open('https://www.instagram.com/arc_bati_architecture','_blank')"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 674,
    "snippet": "</button> <button type=\"button\" onclick=\"soon('LinkedIn — bientôt disponible')\">in</button> <button type"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 675,
    "snippet": "</button> <button type=\"button\" onclick=\"soon('TikTok @arc_bati_architecture — bientôt')\">tt</button> </di"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 678,
    "snippet": "> </div> <div class=\"chip\" onclick=\"window.location.href='/p1'\">Concevoir</div> <div class=\"chip\" onc"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 679,
    "snippet": "Concevoir</div> <div class=\"chip\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20cl%C3"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 680,
    "snippet": "é en main</div> <div class=\"chip\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20fonci"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 697,
    "snippet": "role=\"menu\"> <a href=\"/p1\" onclick=\"window.location.href='/p1';return false;\"> <strong>Projet"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 701,
    "snippet": "</a> <a href=\"#\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20diagn"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 705,
    "snippet": "</a> <a href=\"#\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20cl%C3"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 709,
    "snippet": "</a> <a href=\"#\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20analy"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 713,
    "snippet": "</a> <a href=\"#\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20rappo"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 717,
    "snippet": "</a> <a href=\"#\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20rejoi"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 725,
    "snippet": "<a class=\"pill\" href=\"#medias\" onclick=\"scrollToId('medias');return false;\">Médias</a> <!-- Vente abo"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 728,
    "snippet": "vice) --> <div class=\"pill vip\" onclick=\"openSubModal('vip')\">VIP</div> <div class=\"pill vvip\" onclick=\""
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 729,
    "snippet": "IP</div> <div class=\"pill vvip\" onclick=\"openSubModal('vvip')\">VVIP</div> <a class=\"pill\" href=\"#\" oncl"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 731,
    "snippet": "/div> <a class=\"pill\" href=\"#\" onclick=\"soon('Panier activé après tunnel de commande');return false;\">Panier</a"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 735,
    "snippet": "<button class=\"lang-btn active\" onclick=\"setLang('fr')\">FR</button> <button class=\"lang-btn\" onclick=\""
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 736,
    "snippet": "ton> <button class=\"lang-btn\" onclick=\"setLang('ar')\">AR</button> <button class=\"lang-btn\" onclick=\""
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 737,
    "snippet": "ton> <button class=\"lang-btn\" onclick=\"setLang('en')\">EN</button> </div> <!-- AUTH BUTTONS --"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 761,
    "snippet": "tsApp) --> <article class=\"cat\" onclick=\"window.location.href='/p1'\"> <h3>Projet personnel / familial<"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 767,
    "snippet": "/article> <article class=\"cat\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20diagn"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 773,
    "snippet": "/article> <article class=\"cat\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20cl%C3"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 779,
    "snippet": "/article> <article class=\"cat\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20analy"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 785,
    "snippet": "/article> <article class=\"cat\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20rappo"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 791,
    "snippet": "/article> <article class=\"cat\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20rejoi"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 825,
    "snippet": "elect> <button type=\"button\" onclick=\"autoOrient()\">Être orienté vers la bonne catégorie</button> </d"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 838,
    "snippet": "on class=\"mbtn secondary\" type=\"button\" onclick=\"soon('Démo vidéo sera disponible en lecture interne.')\">Voir</button>"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 839,
    "snippet": "tton class=\"mbtn primary\" type=\"button\" onclick=\"scrollToId('medias')\">Aller aux Médias</button> </div> </"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 852,
    "snippet": "on class=\"mbtn secondary\" type=\"button\" onclick=\"openSubModal('vip')\">VIP</button> <button class=\"mbtn primary"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 853,
    "snippet": "tton class=\"mbtn primary\" type=\"button\" onclick=\"openSubModal('vvip')\">VVIP</button> </div> </div> </a"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 870,
    "snippet": "oppScroller\"> <div class=\"tile\" onclick=\"soon('Détail opportunité: visible dans Médias / VIP selon type.');\">"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 882,
    "snippet": "</div> <div class=\"tile\" onclick=\"soon('Détail opportunité: visible dans Médias / VIP selon type.');\">"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 894,
    "snippet": "</div> <div class=\"tile\" onclick=\"soon('Bientôt.');\"> <div class=\"thumb\"> <div clas"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 945,
    "snippet": "nt --> <div class=\"modal\" id=\"subModal\" onclick=\"modalBackdropClose(event,'subModal')\"> <div class=\"modal-card\" role=\""
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 949,
    "snippet": "span> <button class=\"modal-close\" onclick=\"closeModal('subModal')\">Retour</button> </div> <div class=\"moda"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 960,
    "snippet": "\"> <button class=\"mbtn primary\" onclick=\"window.open('https://wa.me/212700127892?text=Salam%20Yassine%2C%20je%20"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 961,
    "snippet": "<button class=\"mbtn secondary\" onclick=\"closeModal('subModal')\">Plus tard</button> </div> </div> </"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 968,
    "snippet": ") --> <div class=\"modal\" id=\"leadModal\" onclick=\"modalBackdropClose(event,'leadModal')\"> <div class=\"modal-card\" role="
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 972,
    "snippet": "span> <button class=\"modal-close\" onclick=\"closeModal('leadModal')\">Retour</button> </div> <div class=\"mod"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 995,
    "snippet": "\"> <button class=\"mbtn primary\" onclick=\"submitLead()\">Envoyer via plateforme</button> <button class=\"mb"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 996,
    "snippet": "<button class=\"mbtn secondary\" onclick=\"closeModal('leadModal')\">Annuler</button> </div> </div> </d"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1006,
    "snippet": "--> <div class=\"modal\" id=\"submitModal\" onclick=\"modalBackdropClose(event,'submitModal')\"> <div class=\"modal-card\" sty"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1010,
    "snippet": "span> <button class=\"modal-close\" onclick=\"closeModal('submitModal')\">Retour</button> </div> <div class=\"m"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1048,
    "snippet": "\"> <button class=\"mbtn primary\" onclick=\"submitArticle()\" style=\"flex:1;\">Envoyer pour mod&eacute;ration</button"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1049,
    "snippet": "<button class=\"mbtn secondary\" onclick=\"closeModal('submitModal')\">Annuler</button> </div> <p style"
  },
  {
    "kind": "inline_onclick",
    "file": "src/ui/landing/LandingV4.tsx",
    "line": 1068,
    "snippet": "{ // Minimal global helpers used by onclick=\"...\" in the injected HTML. ensureGlobal(\"openModal\", (id: string) ="
  },
  {
    "kind": "href_hash",
    "file": "src/ui/dev/DevRoutesPage.tsx",
    "line": 93,
    "snippet": "liste des patterns à risque (ex: <code>href=\"#\"</code>, inline <code>onclick</code>). Ce n’est pas une preuve qu’un bou"
  }
] as const;
